function [fitresult, gof] = kineticsrational(t, a)
%CREATEFIT(T,A)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : t
%      Y Output: a
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 11-Sep-2023 13:55:49


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( t, a );

% Set up fittype and options.
ft = fittype( 'rat44' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.934010684229183 0.12990620847373 0.568823660872193 0.469390641058206 0.0119020695012414 0.337122644398882 0.162182308193243 0.794284540683907 0.311215042044805];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'a vs. t', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 't', 'Interpreter', 'none' );
% ylabel( 'a', 'Interpreter', 'none' );
% grid on


