function [fitresult, gof] = stepfittingreactionkinetics_NLLS(T,alpha,lowerLimit,upperLimit)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 08-Jul-2023 07:33:45

%% READ IF REGENERATE WITH NEW FUNCTION
% If you change the function just update the inputs to include two
% additional variables lowerLimit and upperLimit. Then store these values
% int the opts.Lower and opts.Upper.


%% Fit
[xData, yData] = prepareCurveData( T, alpha );

% Set up fittype and options.
ft = fittype( 'au-(au.^(1-n)-(1-n).*k.*x).^(1./(1-n))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = lowerLimit;
opts.StartPoint = [0.913375856139019 0.63235924622541 0.0975404049994095];
opts.Upper = upperLimit;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );
